# taken from 
# https://circleci.com/blog/rust-ci/
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.50.0
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: ls
          command: "ls; ls /home/circleci/project/"
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - build-debug-cache-{{ checksum "Cargo.lock" }}
      - run:
          name: Install deps
          command: "cargo build"
      - run:
          name: Run Tests
          command: "cargo test"
      - save_cache:
          key: build-debug-cache-{{ checksum "Cargo.lock" }}
          paths:
            - target/debug/
